version: '3.3'

services:
        api:
                build: .

        nginx:
                image: nginx:latest
                volumes:
                        - ./conf.d:/etc/nginx/conf.d
                depends_on:
                        - api
                ports:
                        - 2381:2381
