version: '3.3'

services:
        public_loadbalancer:
                image: nginx:latest
                volumes:
                        - ./conf.d/loadBalancer:/etc/nginx/conf.d
                depends_on:
                        - api
                ports:
                        - 2381:2381
                networks:
                        - front

        api:
                build: .
                networks:
                        - back

        nginx:
                image: nginx:latest
                volumes:
                        - ./conf.d/nginx:/etc/nginx/conf.d
                depends_on:
                        - api
                          #ports:
                          #- 2381:2381
                networks:
                        - front
                        - back
networks:
        front:
        back:
